version: "3.9"
services:
  web:
    image: isadora145/vet-docker:v3
    container_name: web_vet
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    environment:
      - APP_ENV=local
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
    command: sh -c "
          while ! php -r 'try { new PDO(\"mysql:host=mysql;dbname=\laravel\", \"\laravel_user\", \"\laravel_password\"); } catch (PDOException \$e) { exit(1); }'; do
            echo 'Waiting for MySQL to be ready...';
            sleep 5;
          done;
          echo 'MySQL is up - executing command';
          php artisan migrate --force && php artisan db:seed --force &&
          /usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
    depends_on:
      - mysql
    
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    