version: "3.9"
services:
  web:
    image: isadora145/vet-docker:v2.2
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    environment:
      - APP_ENV=local
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
    command: sh -c "php artisan migrate --force && php artisan db:seed --force && /usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
    depends_on:
      - mysql
    
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    